// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCTws8W3sDGLxIuxHj5X00ckasJhxBaaJs',
    appId: '1:939702805071:web:5b40916c12194756c2c03a',
    messagingSenderId: '939702805071',
    projectId: 'spargo-app',
    authDomain: 'spargo-app.firebaseapp.com',
    storageBucket: 'spargo-app.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCzm9R5O_fwLabBnve2SejGHy96202LWyM',
    appId: '1:939702805071:android:6f8618d46bd56c6cc2c03a',
    messagingSenderId: '939702805071',
    projectId: 'spargo-app',
    storageBucket: 'spargo-app.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBtPN-gFzZwXhNZE-FQzZOGuuWwEX4aRz4',
    appId: '1:939702805071:ios:30d6e7274bfa9006c2c03a',
    messagingSenderId: '939702805071',
    projectId: 'spargo-app',
    storageBucket: 'spargo-app.firebasestorage.app',
    iosBundleId: 'com.spargointeractive.spargo',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBtPN-gFzZwXhNZE-FQzZOGuuWwEX4aRz4',
    appId: '1:939702805071:ios:30d6e7274bfa9006c2c03a',
    messagingSenderId: '939702805071',
    projectId: 'spargo-app',
    storageBucket: 'spargo-app.firebasestorage.app',
    iosBundleId: 'com.spargointeractive.spargo',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCTws8W3sDGLxIuxHj5X00ckasJhxBaaJs',
    appId: '1:939702805071:web:7243ba0503bdd48ac2c03a',
    messagingSenderId: '939702805071',
    projectId: 'spargo-app',
    authDomain: 'spargo-app.firebaseapp.com',
    storageBucket: 'spargo-app.firebasestorage.app',
  );
}
